# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  # Do not pay attention to this parameter
  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vm.provider :virtualbox do |vb|
      config.vbguest.auto_update = false
    end
  end

  # Define the VM
  config.vm.define "centos_server" do |server|
    # Specify the Vagrant box to use
    server.vm.box = "centos/7"
    # Specify the VM specs when using the Virtualbox provisioner
    server.vm.provider "virtualbox" do |vb|
      vb.name =  "centos.server.local"
      # VM RAM in MB
      vb.memory = 13000
      # VM CPUs
      vb.cpus = 8
    end
    config.vm.provider "vmware_desktop" do |vmware|
      vmware.vmx["memsize"] = "2048"
      vmware.vmx["numvcpus"] = "1"
    end
        # Sync application folder to VM
      server.vm.synced_folder "../user-api", "/home/vagrant/app", type: "virtualbox"

        # Use Ansible for provisioning
      server.vm.provision "ansible" do |ansible|
        ansible.playbook = "playbooks/provision.yml"
      end
  end
end
