name: CI/CD Pipeline for Netlify

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      #  Check out the code
      - name: Checkout Code
        uses: actions/checkout@v3

      #  Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Navigate to the user-api folder
        run: cd user-api

      # Install dependencies
      - name: Install Dependencies
        run: npm install
        working-directory: user-api

      # Run tests
      - name: Run Tests
        run: npm test
        working-directory: user-api

      #  Build the project (si vous avez une étape de build)
      - name: Build Project
        run: npm run build
        working-directory: user-api

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Deploy to Netlify
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2.1
        with:
          publish-dir: ./build
          production-deploy: true
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
